# --- !Ups



CREATE TABLE DAS_USER (
  ID INTEGER NOT NULL PRIMARY KEY,
  NAME VARCHAR NOT NULL,
  PASSWORD VARCHAR NOT NULL
);

CREATE TABLE SCHEME_CLAIM(
  EMPREF VARCHAR NOT NULL UNIQUE,
  DAS_USER_ID LONG NOT NULL REFERENCES DAS_USER,
  ACCESS_TOKEN VARCHAR NOT NULL,
  VALID_UNTIL DATE NOT NULL,
  REFRESH_TOKEN VARCHAR NULL
);




# --- !Downs

DROP TABLE SCHEME_CLAIM;
DROP TABLE DAS_USER;